apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python-app
  name: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
    spec:
      containers:
      - image: andriisobchuk/python-app:latest
        name: python-app
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          limits:
            memory: "300Mi"
            cpu: "100m"
          requests:
            memory: "200Mi"
            cpu: "100m"
status: {}

#service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-app
  name: python-app
  namespace: default
spec:
  clusterIP:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: python-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

#horizontal scalling
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: python-app
  name: autoscaling-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 75
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 75
